-- ============================================================================
-- Script: create_tables.sql (CORREGIDO)
-- Descripción: Crear todas las tablas del sistema
-- ============================================================================

SET SERVEROUTPUT ON;

PROMPT Iniciando creación de tablas...

-- Primero, limpiar si existen tablas anteriores
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HORARIO_DISPONIBLE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ASIGNACION_GUIA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE RESERVA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE GUIA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE VISITANTE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SENDERO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SENDERO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVA';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ASIGNACION';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HORARIO';
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Primera ejecución - no hay tablas que eliminar.
END;
/

-- ============================================================================
-- TABLA: USUARIO (Base para herencia)
-- ============================================================================
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    CEDULA VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(15),
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(20) NOT NULL CHECK (ROL IN ('ADMIN', 'GUIA', 'VISITANTE')),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO', 'ELIMINADO')),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_EMAIL_FORMAT CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

-- Índices para Usuario (EMAIL y CEDULA ya tienen índice por UNIQUE, no crear duplicados)
CREATE INDEX IDX_USUARIO_ROL ON USUARIO(ROL);
CREATE INDEX IDX_USUARIO_ESTADO ON USUARIO(ESTADO);

PROMPT Tabla USUARIO creada.

-- ============================================================================
-- TABLA: VISITANTE (Herencia de Usuario)
-- ============================================================================
CREATE TABLE VISITANTE (
    ID_USUARIO NUMBER PRIMARY KEY,
    NUMERO_VISITAS NUMBER DEFAULT 0,
    PUNTUACION_PROMEDIO NUMBER(3,2) DEFAULT 0.00,
    CONSTRAINT FK_VISITANTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_PUNTUACION CHECK (PUNTUACION_PROMEDIO >= 0 AND PUNTUACION_PROMEDIO <= 5)
);

PROMPT Tabla VISITANTE creada.

-- ============================================================================
-- TABLA: GUIA (Herencia de Usuario)
-- ============================================================================
CREATE TABLE GUIA (
    ID_USUARIO NUMBER PRIMARY KEY,
    ESPECIALIDADES VARCHAR2(200),
    MAX_PERSONAS_GRUPO NUMBER DEFAULT 15,
    CALIFICACION_PROMEDIO NUMBER(3,2) DEFAULT 0.00,
    NUMERO_RECORRIDOS NUMBER DEFAULT 0,
    CONSTRAINT FK_GUIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_MAX_PERSONAS CHECK (MAX_PERSONAS_GRUPO > 0 AND MAX_PERSONAS_GRUPO <= 30),
    CONSTRAINT CHK_CALIFICACION CHECK (CALIFICACION_PROMEDIO >= 0 AND CALIFICACION_PROMEDIO <= 5)
);

PROMPT Tabla GUIA creada.

-- ============================================================================
-- TABLA: SENDERO
-- ============================================================================
CREATE TABLE SENDERO (
    ID_SENDERO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION CLOB,
    DIFICULTAD VARCHAR2(20) NOT NULL CHECK (DIFICULTAD IN ('FACIL', 'MODERADO', 'DIFICIL', 'EXPERTO')),
    DURACION_HORAS NUMBER(3,1) NOT NULL,
    CUPO_MAXIMO_DIA NUMBER NOT NULL,
    DISTANCIA_KM NUMBER(5,2) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    IMAGEN_URL VARCHAR2(500),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_DURACION CHECK (DURACION_HORAS > 0),
    CONSTRAINT CHK_CUPO CHECK (CUPO_MAXIMO_DIA > 0),
    CONSTRAINT CHK_DISTANCIA CHECK (DISTANCIA_KM > 0)
);

-- Índices para Sendero
CREATE INDEX IDX_SENDERO_DIFICULTAD ON SENDERO(DIFICULTAD);
CREATE INDEX IDX_SENDERO_ESTADO ON SENDERO(ESTADO);

PROMPT Tabla SENDERO creada.

-- ============================================================================
-- TABLA: RESERVA (SIN CHECK de fecha con SYSDATE)
-- ============================================================================
CREATE TABLE RESERVA (
    ID_RESERVA NUMBER PRIMARY KEY,
    ID_VISITANTE NUMBER NOT NULL,
    ID_SENDERO NUMBER NOT NULL,
    FECHA_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_VISITA DATE NOT NULL,
    NUMERO_PERSONAS NUMBER NOT NULL,
    HORA_INICIO TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', 'NO_ASISTIO')),
    OBSERVACIONES VARCHAR2(500),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_CANCELACION TIMESTAMP,
    MOTIVO_CANCELACION VARCHAR2(200),
    CONSTRAINT FK_RESERVA_VISITANTE FOREIGN KEY (ID_VISITANTE) REFERENCES VISITANTE(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_RESERVA_SENDERO FOREIGN KEY (ID_SENDERO) REFERENCES SENDERO(ID_SENDERO) ON DELETE CASCADE,
    CONSTRAINT CHK_NUM_PERSONAS CHECK (NUMERO_PERSONAS >= 1 AND NUMERO_PERSONAS <= 20)
    -- NOTA: La validación de fecha futura se hace en el trigger TRG_VALIDAR_ANTICIPACION
);

-- Índices para Reserva
CREATE INDEX IDX_RESERVA_VISITANTE ON RESERVA(ID_VISITANTE);
CREATE INDEX IDX_RESERVA_SENDERO ON RESERVA(ID_SENDERO);
CREATE INDEX IDX_RESERVA_FECHA ON RESERVA(FECHA_VISITA);
CREATE INDEX IDX_RESERVA_ESTADO ON RESERVA(ESTADO);

PROMPT Tabla RESERVA creada.

-- ============================================================================
-- TABLA: ASIGNACION_GUIA
-- ============================================================================
CREATE TABLE ASIGNACION_GUIA (
    ID_ASIGNACION NUMBER PRIMARY KEY,
    ID_RESERVA NUMBER NOT NULL UNIQUE,
    ID_GUIA NUMBER NOT NULL,
    FECHA_ASIGNACION DATE DEFAULT SYSDATE,
    HORA_INICIO_REAL TIMESTAMP,
    HORA_FIN_REAL TIMESTAMP,
    OBSERVACIONES_GUIA VARCHAR2(500),
    CALIFICACION_VISITANTE NUMBER(1),
    COMENTARIO_VISITANTE VARCHAR2(300),
    INCIDENCIAS NUMBER(1) DEFAULT 0 CHECK (INCIDENCIAS IN (0, 1)),
    DESCRIPCION_INCIDENCIAS VARCHAR2(500),
    CONSTRAINT FK_ASIGNACION_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA) ON DELETE CASCADE,
    CONSTRAINT FK_ASIGNACION_GUIA FOREIGN KEY (ID_GUIA) REFERENCES GUIA(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_CALIFICACION_VIS CHECK (CALIFICACION_VISITANTE IS NULL OR (CALIFICACION_VISITANTE >= 1 AND CALIFICACION_VISITANTE <= 5))
);

-- Índices para AsignacionGuia
CREATE INDEX IDX_ASIGNACION_GUIA ON ASIGNACION_GUIA(ID_GUIA);
CREATE INDEX IDX_ASIGNACION_FECHA ON ASIGNACION_GUIA(FECHA_ASIGNACION);

PROMPT Tabla ASIGNACION_GUIA creada.

-- ============================================================================
-- TABLA: HORARIO_DISPONIBLE
-- ============================================================================
CREATE TABLE HORARIO_DISPONIBLE (
    ID_HORARIO NUMBER PRIMARY KEY,
    ID_SENDERO NUMBER NOT NULL,
    HORA_INICIO TIMESTAMP NOT NULL,
    HORA_FIN TIMESTAMP NOT NULL,
    CUPO_HORARIO NUMBER NOT NULL,
    DIAS_SEMANA VARCHAR2(50) DEFAULT 'L,M,MI,J,V,S,D',
    ACTIVO NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT FK_HORARIO_SENDERO FOREIGN KEY (ID_SENDERO) REFERENCES SENDERO(ID_SENDERO) ON DELETE CASCADE,
    CONSTRAINT CHK_CUPO_HORARIO CHECK (CUPO_HORARIO > 0)
);

-- Índices para HorarioDisponible
CREATE INDEX IDX_HORARIO_SENDERO ON HORARIO_DISPONIBLE(ID_SENDERO);

PROMPT Tabla HORARIO_DISPONIBLE creada.

-- ============================================================================
-- SEQUENCES (para IDs autoincrementales)
-- ============================================================================
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SENDERO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ASIGNACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HORARIO START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT Sequences creadas.

PROMPT ============================================================
PROMPT Todas las tablas creadas exitosamente.
PROMPT ============================================================
